### mainnet

[package]
name = "MoleVault"
version = "1.0.0"
# updated version
published-at = "0x2fa2bf0ab35d3f75acec536041cc3f885114a1b54334aecde01d6c551c51ca5d"

[addresses]
# first verion 
mole_vault = "0x5ffa69ee4ee14d899dcc750df92de12bad4bacf81efa1ae12ee76406804dda7f"

[dependencies]
Mole = {local = "../mole"}
MoleWorker = {local = "../mole_worker"}


