### mainnet

[package]
name = "MoleVault"
version = "1.0.0"
# 
published-at = "0x5ffa69ee4ee14d899dcc750df92de12bad4bacf81efa1ae12ee76406804dda7f"

[addresses]
mole_vault = "0x5ffa69ee4ee14d899dcc750df92de12bad4bacf81efa1ae12ee76406804dda7f"

[dependencies]
Mole = {local = "../mole"}
MoleWorker = {local = "../mole_worker"}


