### mainnet

[package]
name = "MoleVault"
version = "1.0.0"
# updated version
published-at = "0x02f3046dcbbee703e89dfdba5c73846dc0e4d0fbb33c581ab0498faf2db0a78d"

[addresses]
# first verion 
mole_vault = "0x5ffa69ee4ee14d899dcc750df92de12bad4bacf81efa1ae12ee76406804dda7f"

[dependencies]
Mole = {local = "../mole"}
MoleWorker = {local = "../mole_worker"}


